export default {
  login: 'sam4web',
  id: 70482531,
  node_id: 'MDQ6VXNlcjcwNDgyNTMx',
  avatar_url: 'https://avatars.githubusercontent.com/u/70482531?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/sam4web',
  html_url: 'https://github.com/sam4web',
  followers_url: 'https://api.github.com/users/sam4web/followers',
  following_url: 'https://api.github.com/users/sam4web/following{/other_user}',
  gists_url: 'https://api.github.com/users/sam4web/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/sam4web/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/sam4web/subscriptions',
  organizations_url: 'https://api.github.com/users/sam4web/orgs',
  repos_url: 'https://api.github.com/users/sam4web/repos',
  events_url: 'https://api.github.com/users/sam4web/events{/privacy}',
  received_events_url: 'https://api.github.com/users/sam4web/received_events',
  type: 'User',
  site_admin: false,
  name: 'Sijal Manandhar',
  company: null,
  blog: 'https://www.sijalmanandhar.com.np',
  location: null,
  email: null,
  hireable: null,
  bio: "I'm a dedicated Front-end Web Developer, focused on designing and developing websites and web applications.",
  twitter_username: null,
  public_repos: 30,
  public_gists: 0,
  followers: 7,
  following: 17,
  created_at: '2020-08-30T16:42:30Z',
  updated_at: '2024-05-27T15:08:19Z',
};
