export default {
  login: 'bchiang7',
  id: 6599979,
  node_id: 'MDQ6VXNlcjY1OTk5Nzk=',
  avatar_url: 'https://avatars.githubusercontent.com/u/6599979?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/bchiang7',
  html_url: 'https://github.com/bchiang7',
  followers_url: 'https://api.github.com/users/bchiang7/followers',
  following_url: 'https://api.github.com/users/bchiang7/following{/other_user}',
  gists_url: 'https://api.github.com/users/bchiang7/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/bchiang7/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/bchiang7/subscriptions',
  organizations_url: 'https://api.github.com/users/bchiang7/orgs',
  repos_url: 'https://api.github.com/users/bchiang7/repos',
  events_url: 'https://api.github.com/users/bchiang7/events{/privacy}',
  received_events_url: 'https://api.github.com/users/bchiang7/received_events',
  type: 'User',
  site_admin: false,
  name: 'Brittany Chiang',
  company: null,
  blog: 'https://brittanychiang.com',
  location: null,
  hireable: true,
  bio: "I'm a dedicated Front-end Web Developer, focused on designing and developing websites and web applications.",
  twitter_username: 'asdf',
  public_repos: 61,
  public_gists: 26,
  followers: 8898,
  following: 13,
  created_at: '2014-02-05T23:22:59Z',
  updated_at: '2024-05-27T11:23:59Z',
};
